include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters
    - use_enums
    - always_use_package_imports
    - use_decorated_box
    - use_colored_box
    - unnecessary_late
    - unnecessary_constructor_name
    - sized_box_shrink_expand
    - secure_pubspec_urls
    - avoid_positional_boolean_parameters
    - sort_pub_dependencies
    - use_named_constants
    - literal_only_boolean_expressions
    - prefer_final_in_for_each
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - avoid_print
    - file_names
    - no_logic_in_create_state
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_function_declarations_over_variables
    - prefer_inlined_adds
    - unnecessary_overrides
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_full_hex_values_for_flutter_colors
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - unnecessary_await_in_return
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - prefer_final_locals
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - eol_at_end_of_file
    # - lines_longer_than_80_chars
    # - no_default_cases
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_closures
    # - omit_local_variable_types
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - prefer_equal_for_default_values
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_spread_collections
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_this
    - use_is_even_rather_than_modulo
    - use_if_null_to_convert_nulls_to_bools
    - void_checks
