name: yaca
description: "Yet another crypto app"
repository: https://github.com/georgeherby/yaca
issue_tracker: https://github.com/georgeherby/yaca/issues
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1-0 <3.0.0" # Dart
  flutter: ^3.0.1

dependencies:
  auto_route: ^4.0.1
  cached_network_image: ^3.2.1
  coingecko_api: ^1.0.2+2
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  firebase_analytics: ^9.1.8
  firebase_core: ^1.17.0
  firebase_performance: ^0.9.0
  fl_chart: ^0.50.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.3
  flutter_native_splash: ^2.2.0+1
  flutter_platform_widgets: ^1.20.0
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  ionicons: ^0.1.2
  macos_ui: ^1.4.1+1
  palette_generator: ^0.3.3
  path_provider: ^2.0.10
  provider: ^6.0.2
  responsive_builder:
    git:
      url: https://github.com/georgeherby/responsive_builder.git
      ref: master
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.2

flutter_icons:
  android: false
  ios: true
  windows: false
  web: true
  image_path: "assets/icon-1024.png"

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_launcher_icons:
    git:
      url: https://github.com/dirkbo/flutter_launcher_icons.git
      ref: desktop_linux_
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/whale_outline.svg
    - assets/whale_filled.svg
    - assets/logo.svg
    - assets/flame.svg
    - assets/crypto_icons/btc.svg
    - assets/crypto_icons/eth.svg
    - assets/crypto_icons/ltc.svg
    - assets/fiat_icons/eur.svg
    - assets/fiat_icons/gbp.svg
    - assets/fiat_icons/usd.svg

import_sorter:
  emojis: true
  comments: true
