name: yaca
description: "Yet another crypto app"
repository: https://github.com/georgeherby/yaca
issue_tracker: https://github.com/georgeherby/yaca/issues
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-0 <3.0.0" # Dart

dependencies:
  auto_route: ^4.2.1
  cached_network_image: ^3.2.1
  coingecko_api: ^1.0.2+2
  cupertino_icons: ^1.0.5
  entry: ^0.0.7
  equatable: ^2.0.3
  firebase_analytics: ^9.1.12
  firebase_core: ^1.19.1
  firebase_performance: ^0.8.1+1
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_html: ^3.0.0-alpha.5
  flutter_native_splash: ^2.2.4
  flutter_platform_widgets: ^2.0.0
  flutter_svg: ^1.1.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  macos_ui: ^1.5.1
  palette_generator: ^0.3.3+1
  path_provider: ^2.0.11
  provider: ^6.0.3
  responsive_builder:
    git:
      url: https://github.com/georgeherby/responsive_builder.git
      ref: master
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.4

flutter_icons:
  android: false
  ios: true
  windows: false
  web: true
  image_path: "assets/icon-1024.png"

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.1.0
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  flutter_launcher_icons:
    git:
      url: https://github.com/dirkbo/flutter_launcher_icons.git
      ref: desktop_linux_
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/whale_outline.svg
    - assets/whale_filled.svg
    - assets/logo.svg
    - assets/flame.svg
    - assets/crypto_icons/btc.svg
    - assets/crypto_icons/eth.svg
    - assets/crypto_icons/ltc.svg
    - assets/fiat_icons/eur.svg
    - assets/fiat_icons/gbp.svg
    - assets/fiat_icons/usd.svg

import_sorter:
  emojis: true
  comments: true
