name: crypto_app
description: View crpytocurrency data

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.3-0 <3.0.0" # Dart
  flutter: ^2.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  cupertino_icons: ^1.0.3
  fl_chart: ^0.36.4
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  path_provider: ^2.0.5
  sqflite: ^2.0.0+4
  shimmer: ^2.0.0
  url_launcher: ^6.0.12
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  pedantic: ^1.11.0
  google_fonts: ^2.1.0
  responsive_builder: ^0.4.1
  font_awesome_flutter: ^9.1.0
  macos_ui: ^0.7.2
  flutter_html: ^2.1.5
  flutter_platform_widgets: ^1.9.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  bloc_test: ^8.3.0
  mocktail: ^0.1.4
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/whale_outline.svg
    - assets/whale_filled.svg

import_sorter:
  emojis: true
  comments: true
