name: crypto_app
description: View crpytocurrency data

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
    ^0.13.3
    #^0.12.2
  intl: ^0.17.0
  # decimal: 1.0.0-nullsafety
  cupertino_icons: ^1.0.3
  fl_chart: ^0.36.1
  provider: ^5.0.0
  # dart_rss: ^1.0.1
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  sqflite: ^2.0.0+2
  shimmer: ^2.0.0
  # flutter_svg: ^0.20.0-nullsafety.3
  url_launcher: ^6.0.3
  flutter_bloc: ^7.0.0
  # equatable: ^2.0.0-nullsafety.1
  equatable: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  pedantic: ^1.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/001-whale.svg
    - assets/002-whale-1.svg
