name: yaca
description: "Yet another crypto app"
repository: https://github.com/georgeherby/yaca
issue_tracker: https://github.com/georgeherby/yaca/issues
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-0 <3.0.0" # Dart
  flutter: ^2.8.1

dependencies:
  auto_route: ^3.2.0
  cached_network_image: ^3.1.0+1
  equatable: ^2.0.3
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_performance: ^0.8.0+3
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^2.2.1
  flutter_native_splash: ^1.3.2
  flutter_platform_widgets: ^1.12.1
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  ionicons: ^0.1.2
  macos_ui: ^0.10.0+1
  palette_generator: ^0.3.2
  path_provider: ^2.0.7
  provider: ^6.0.2
  responsive_builder:
    git:
      url: https://github.com/georgeherby/responsive_builder.git
      ref: master
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  url_launcher: ^6.0.15

dependency_overrides:
  flutter_svg: ^1.0.0

flutter_icons:
  android: false
  ios: true
  windows: false
  web: true
  image_path: "assets/icon-1024.png"

dev_dependencies:
  flutter_launcher_icons:
    git:
      url: https://github.com/dirkbo/flutter_launcher_icons.git
      ref: desktop_linux_
  auto_route_generator: ^3.2.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  import_sorter: ^4.6.0
  mocktail: ^0.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/whale_outline.svg
    - assets/whale_filled.svg
    - assets/logo.svg
    - assets/crypto_icons/btc.svg
    - assets/crypto_icons/eth.svg
    - assets/crypto_icons/ltc.svg
    - assets/fiat_icons/eur.svg
    - assets/fiat_icons/gbp.svg
    - assets/fiat_icons/usd.svg

import_sorter:
  emojis: true
  comments: true
