name: crypto_app
description: View crpytocurrency data

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.3-0 <3.0.0" # Dart
  flutter: ^2.5.2

dependencies:
  auto_route: ^3.0.4
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_html: ^2.1.5
  flutter_platform_widgets: ^1.9.5
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  macos_ui: ^0.10.0+1  
  palette_generator: ^0.3.2
  path_provider: ^2.0.6 
  pedantic: ^1.11.0
  provider: ^6.0.0
  responsive_builder:
    git:
      url: git://github.com/georgeherby/responsive_builder.git
      ref: master
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.12

dev_dependencies:
  auto_route_generator: ^3.0.1
  bloc_test: ^8.4.0  
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  import_sorter: ^4.6.0
  mocktail: ^0.2.0   
flutter:
  uses-material-design: true
  assets:
    - assets/whale_outline.svg
    - assets/whale_filled.svg

import_sorter:
  emojis: true
  comments: true
